simulator/CMakeLists.txt

Now using `cmake --build build -t run` can output log in real time.

cmake(simulator): print log to terminal when using cmake with target `run`

---

simulator/main.c
src/event.c
src/luavgl.h
src/obj.c
src/private.h

Only lua created obj can add event callback, and it makes logic much simpler.
Fix #10
Depends on the dsc returned from add_event, need to wait lvgl merge this change firstly.

event: simplify event porting by leveraging lvgl's event dsc handler

---

src/constants.c

Image and Label widgets are essential to lvgl, thus cannot be disabled for now. Other supported widgets can now be disabled separately.

constants: fix compiler error when widgets are disabled

---

src/font.c

Fix #9 
Use max 16byte for named weight string instead of variable lenght array.

fix(font): avoid using varaible length array

---

.gitignore
README.md
examples/flappyBird/flappyBird.lua
simulator/lv_conf.h
simulator/main.c
simulator/widgets/lv_analog_time.c
xmake.lua

1.The gameover image plays an animation when the bird dies, and if you click the restart button before the animation finishes, it will cause the animation's callback function to call an empty object.
2.The emulator is supported to be compiled under windows using xmake, and it can be compiled and run under Ubuntu as well.
```bash
xmake b simulator
xmake r simulator
```

Fixed example of flappyBird gameover restarting too fast causing an anomaly and Support for windows compilation

---

simulator/lv_conf.h

`LV_FS_STDIO_PLAT_LETTER` is defined in xmake but not cmake.
```
/home/neo/projects/lvgl/luavgl/simulator/lv_conf.h:612:32: error: ‘LV_FS_STDIO_PLAT_LETTER’ undeclared (first use in this function); did you mean ‘LV_FS_STDIO_LETTER’?
612 |     #define LV_FS_STDIO_LETTER LV_FS_STDIO_PLAT_LETTER     /*Set an upper cased letter on which the drive will accessible (e.g. 'A')*/
|                                ^~~~~~~~~~~~~~~~~~~~~~~
/home/neo/projects/lvgl/luavgl/deps/lvgl/src/libs/fsdrv/lv_fs_stdio.c:76:24: note: in expansion of macro ‘LV_FS_STDIO_LETTER’
76 |     fs_drv_p->letter = LV_FS_STDIO_LETTER;
|                        ^~~~~~~~~~~~~~~~~~
/home/neo/projects/lvgl/luavgl/simulator/lv_conf.h:612:32: note: each undeclared identifier is reported only once for each function it appears in
612 …
```

fix(simulator): fix compile break

---

simulator/lv_conf.h

The examples uses image path starts from "/path/to/image.png", which is supported by FS_POSIX.

fix: enable LV_FS_POSIX

---

src/lvgl.lua
src/obj.c

This allows chain several set methods like:
```lua
obj:add_flag(lvgl.FLAG.SCROLLABLE):center()
```

feat(obj): return obj for all set API

---

src/obj.c

This patch allows to create child obj directly in the property table. To make it looks like children are created recursively.
In fact, with this coding style, the children is created firstly and it's stored to property table with integer key. Simply find them out and set parent for them.
```lua
local lvgl = require("lvgl")
local root = lvgl.Object(nil, {
flex = {
flex_direction = "row",
flex_wrap = "wrap",
justify_content = "center",
align_items = "center",
align_content = "center",
},
w = 300,
h = 75,
align = lvgl.ALIGN.CENTER,
lvgl.Object(nil, {
w = 100,
h = lvgl.PCT(100),
lvgl.Label(nil, {
text = string.format("label %d", 1)
}):center()
}):clear_flag(lvgl.FLAG.SCROLLABLE),
lvgl.Object(nil, {
w = 100,
h = lvgl.PCT(100),
lvgl.Label(nil, {
text = string.format("label %d", 1)
}):center() …
```

feat(obj): allow to create child obj inside property table

---

examples/analogTime.lua
examples/dropdown.lua
examples/examples.lua
examples/extension.lua
examples/flappyBird/flappyBird.lua
examples/flexLayout.lua
examples/font.lua
examples/fs.lua
examples/group.lua
examples/indev.lua
examples/keyboard.lua
examples/pointer.lua
examples/protectedcall.lua
examples/roller.lua
examples/tests.lua
src/obj.c

Check if the first parameter is table, if so, the parent must be nil and default root is used. This allows us to create object on screen easier.
The change is pretty simple.
```diff
@@ -842,7 +842,7 @@ LUALIB_API int luavgl_obj_create_helper(lua_State *L,
luavgl_ctx_t *ctx = luavgl_context(L);
lv_obj_t *parent;
-  if (lua_isnoneornil(L, 1)) {
+  if (lua_type(L, 1) == LUA_TTABLE || lua_isnoneornil(L, 1)) {
parent = ctx->root;
} else {
parent = luavgl_to_obj(L, 1);
```

feat(obj): allow to omit the nil parent

---

.gitmodules
src/luavgl.c
src/rotable.c
src/rotable.h

I haven't done benchmark, the `rotable` definitely will save lots of RAM considering there are lots of constants from lvgl.
- Upgrade `lvgl` to latest master branch.
- Remove `lv_drivers` deps.
- Add rotable from https://github.com/siffiejoe/lua-rotable .
- Tweak rotable to allow to add custom type of table value.

Add rotable support to reduce RAM size

---

src/rotable.c
src/rotable.h

Since rodata's meta table is already used to fake the normal table operation, we use userdata uservalue[2] to store an optional table as meta table. It's further searched when no match found in rodata's __index method.
Fix bug in rotable_newidx.

feat(rotable): add metatable support to rotable

---

examples/examples.lua
src/luavgl.c
src/luavgl.h
src/palette.c
src/util.c

Usage: lvgl.palette.main(lvgl.palette.BLUE_GREY)
Fix #35

feat(palette): add palette API

---

examples/flappyBird/flappyBird.lua
src/obj.c
src/util.c

Fix #61
Try to set property in a fixed order using lvgl's property API for specified class.
Iterate all base classes. 
1. check luavgl property table for a match
2. if not match, check lvgl's property API for this specific class.
If still no match, 
1. check luavgl's style set API.
2. check lvgl's style property.

Fix luavgl obj property API

---

CMakeLists.txt
examples/declarative.lua
examples/examples.lua
src/luavgl.c
src/widgets/button.c
src/widgets/widgets.c

Add declarative example:
```lua
Object {
flex = {
flex_direction = "row",
flex_wrap = "wrap",
justify_content = "center",
align_items = "center",
align_content = "center",
},
w = 400,
h = 100,
align = lvgl.ALIGN.CENTER,
-- Button with label, inside a container
Object {
w = 150,
h = lvgl.PCT(80),
bg_color = "#aa0",
Button {
Label {
text = string.format("BUTTON %d", 1),
align = lvgl.ALIGN.CENTER
}
}:center()
}:clear_flag(lvgl.FLAG.SCROLLABLE),
-- Label inside a container
Object({
w = 150,
h = lvgl.PCT(80),
Label {
text = string.format("label %d", 2)
}:center()
}):clear_flag(lvgl.FLAG.SCROLLABLE)
}
```

Add declarative example

---

examples/examples.lua
examples/luaC.lua
examples/objid.lua
examples/tests.lua
simulator/CMakeLists.txt
simulator/lua_in_C.c
simulator/lv_conf.h
simulator/main.c
src/obj.c

With this update, you can now design your UI in Lua and seamlessly integrate it with C, merging the simplicity of luavgl with the power of C. 
Say goodbye to hundreds of lines of style settings—`luavgl` makes UI creation a breeze!
```c
static const char lua_code_string[] = STRINGIZE(
local root = lvgl.get_child_by_id("luaUIroot")
root.w = lvgl.VER_RES(),
root.h = lvgl.HOR_RES(),
Button(root, {
id = "Button in Lua",
Label {
text = "Hello, lua, C and lvgl!",
align = lvgl.ALIGN_CENTER
}
}):center()
);
static int embed_lua_in_c(lua_State *L)
{
/* We create a root obj in C and create other UIs in lua. */
lv_obj_t *root = lv_obj_create(lv_screen_active());
luavgl_add_lobj(L, root)->lua_created = false;
lv_obj_set_id(root, lv_strdup("luaUIroot"));
luaL_dostring(L, lua_code_string);
return 0;
} …
```

Add example of mixed UI programming with Lua and C

---

examples/luaC.lua
simulator/lua_in_C.c
simulator/ui.lua
src/obj.c

In C
```c
static const char lua_code_string[] = {
#include "ui.lua"
};
```
In lua
```lua
STRINGIZE((function()
local root = lvgl.get_child_by_id("luaUIroot")
root.w = lvgl.VER_RES()
root.h = lvgl.HOR_RES()
Button(root, {
id = "Button in Lua",
Label {
text = "Hello, lua, C and lvgl!",
align = lvgl.ALIGN_CENTER
}
}):center()
end)())
```
The additional (function() end))() is just to make lua happy with the gramma. Treat STRINGIZE is a global function in lua.

Add example of include lua file to C to compile and run

---

simulator/lua_in_C.c
src/luavgl.c
src/lvgl.lua
src/style.c

44b5e9b doc: minor update to include global functions
bca28b3 obj: allow chain set of obj style API
d097625 luavgl: avoid wild pointer in lua context
31b52d2 simulator: remove auto-import headers

Misc update of simulator, obj and doc

---

src/constants.c

When only the Montserrat 14 font is enabled, sigsegv occurs. It is unclear why it was running normally before.

fix(constants.c): end mark for supplementary font table

---

src/obj.c

Lua 5.1 does not have lua_setuservalue, and lua-compat-5.3 uses lua_setfenv, but lua_setfenv only allows tables.

fix(obj): compatible with lua 5.1
